"""
Screener run history -- remembers which tickers each completed screen
returned, so you can look back at "what did last Tuesday's momentum scan
turn up?" without re-running it.

Follows the exact same storage pattern as assistant/watchlist.py: a
simple per-user JSON file through assistant.storage (atomic writes,
automatic backups/recovery -- see that module's docstring). Kept as its
own file/module rather than folded into watchlist.py since it's a
different kind of data (a log of past runs, not a mutable set of
tickers) with its own cap/eviction policy.

Each stored entry is intentionally compact -- ticker, rank, score, and
signal for every row the screen returned, plus the config used and a
timestamp -- NOT the full per-ticker metrics dict (that can be
regenerated by re-running the screen; storing it for every historical
run would make this file grow unbounded for no real benefit).
"""
import threading
import time
import uuid

from .. import storage
from ..config import SCREENER_HISTORY_PATH, SCREENER_HISTORY_MAX_RUNS

_lock = threading.Lock()


def _load():
    return storage.load_json(SCREENER_HISTORY_PATH)


def _save(data):
    storage.save_json(SCREENER_HISTORY_PATH, data)


def record_run(user_id, result, universe_key, preset_key):
    """
    Persist a compact record of a completed screen run. Call this after
    run_screen() returns successfully (not on error/empty-universe
    results) so history reflects real completed scans, matching what a
    user would actually want to look back at.

    Returns the stored entry (including its generated id), so a caller
    can immediately show/link to it if useful.
    """
    entry = {
        "id": uuid.uuid4().hex,
        "timestamp": time.time(),
        "universe": universe_key,
        "preset": preset_key,
        "universe_size": result.get("universe_size"),
        "kronos_ran": bool(result.get("kronos_ran")),
        "elapsed_seconds": result.get("elapsed_seconds"),
        "quality_summary": result.get("quality_summary", {}),
        "tickers": [
            {
                "rank": row.get("rank"),
                "ticker": row.get("ticker"),
                "price": row.get("price"),
                "score": row.get("overall_score"),
                "signal": row.get("signal"),
            }
            for row in result.get("rows", [])
        ],
    }
    with _lock:
        data = _load()
        lst = data.setdefault(str(user_id), [])
        lst.insert(0, entry)  # newest first
        data[str(user_id)] = lst[:SCREENER_HISTORY_MAX_RUNS]
        _save(data)
    return entry


def get_history(user_id, limit=None):
    """Most-recent-first list of past screen runs for this user."""
    with _lock:
        data = _load()
        lst = data.get(str(user_id), [])
        return lst[:limit] if limit else list(lst)


def get_run(user_id, run_id):
    """A single past run by id, or None if it doesn't exist / has aged out."""
    for entry in get_history(user_id):
        if entry.get("id") == run_id:
            return entry
    return None


def clear_history(user_id):
    with _lock:
        data = _load()
        data[str(user_id)] = []
        _save(data)
    return []


def ticker_appearance_count(user_id, ticker):
    """
    How many past screens this ticker showed up in, and at what ranks --
    useful for "AAPL keeps showing up as a top momentum pick" style
    context. Cheap: scans the already-loaded compact history, no network.
    """
    ticker = ticker.upper()
    appearances = []
    for run in get_history(user_id):
        for row in run.get("tickers", []):
            if row.get("ticker", "").upper() == ticker:
                appearances.append({
                    "run_id": run["id"], "timestamp": run["timestamp"],
                    "rank": row.get("rank"), "score": row.get("score"), "signal": row.get("signal"),
                })
                break  # a ticker appears at most once per run
    return appearances
